services:
  app:
    image: firstdraft/appdev-rails-8-template
    volumes:
      - ..:/workspaces/ai-web-search:cached
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/ai_web_search_development
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: ai_web_search_development
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_web_search_development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: