version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: development
    volumes:
      - ..:/workspace:cached
      - bundle:/usr/local/bundle
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/development
      RAILS_ENV: development
    depends_on:
      - db
    command: sleep infinity
    networks:
      - default

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: development
    networks:
      - default

volumes:
  postgres-data:
  bundle:

networks:
  default: